name: staging

on:
  push:
    branches:
      - '**'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
